Models/ErrorViewModel.cs
using System;

namespace testproj.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace testproj.Models
{
    public class Item
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }
        public string ItemId { get; set; }
        public string StorageId { get; set; }
        public string RecipeId { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }

        public string Type { get; } = "item";
        public string Units { get; set; }
    }
}

Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace testproj.Models
{
    public class Recipe
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }
        public string RecipeId { get; set; }
        public string UserId { get; set; }
        public string Type { get; } = "recipe";

        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
    }
}

Models/ShoppingList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace testproj.Models
{
    public class ShoppingList
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }
        public string UserId { get; set; }
        public string ShoppingListId { get; set; }
        public string Type { get; } = "shoppinglist";

        public string Notes { get; set; }
    }
}

Models/ShoppingListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace testproj.Models
{
    public class ShoppingListItem
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }
        public string ShoppingListItemId { get; set; }
        public string ShoppingListId { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }

        public string Type { get; } = "shoppinglistitem";
        public string Units { get; set; }
    }
}

Models/Storage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace testproj.Models
{
    public class Storage
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }
        public string StorageId { get; set; }
        public string UserId { get; set; }
        public string Type { get; } = "storage";
        public string Name { get; set; }
    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace testproj.Models
{
    public class User
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }
        public string UserId { get; set; }

        public string Name { get; set; }

        public string Type { get; } = "user";
    }
}

Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using testproj.Utils;

namespace testproj.Controllers
{
    public class DashboardController : Controller
    {
        ISingleton repo;
        public DashboardController(ISingleton repo)
        {
            this.repo = repo;
        }
        public IActionResult Dashboard()
        {
            //ViewBag.LastVisited = GetLastVisited();
            return View();
        }

        //private LastVisited[] GetLastVisited()
        //{
        //    var lastVisited = repo.GetLastVisited();

        //    return lastVisited;
        //}
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using testproj.Models;

namespace testproj.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StorageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using testproj.Models;
using testproj.Utils;

namespace testproj.Controllers
{
    public class StorageController : Controller
    {
        private Repository repo;
        public StorageController(ISingleton repo)
        {
            this.repo = repo as Repository;
        }
        public IActionResult Storage()
        {
            return View();
        }

        public async Task<IActionResult> Storages()
        {
            var storages = await repo.GetStoragesByUserIdAsync(1);
            ViewBag.StorageNames = storages.Select(s => s.Name);
            return View();
        }

        public IActionResult PostStorage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PostStorage([FromForm] string StorageName)
        {
            await repo.AddStorageAsync(new Storage() { 
                Name = StorageName,
                StorageId = "1",
                UserId = "1",
                Id = "1"
            });
            return View();
        }
    }
}

Views/Dashboard/Dashboard.cshtml
<div class="card">
    <div class="card-header">
        Last Visited
    </div>
    <div class="card-body">
        <ul>
            @foreach (var lastVisitedItem in ViewBag.LastVisited)
            {
            <li><div>@lastVisitedItem.Name</div><div>@lastVisitedItem.LastVisitedDateTime</div></li>
            }
        </ul>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - testproj</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">testproj</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <nav id="sidebar">
                <h2>Sidebar</h2>
                <ul class="list-unstyled components">
                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Storage" asp-action="Storages">Storages</a></li>
                    <li><a>Test2</a></li>
                    <li><a>Test3</a></li>
                    <li><a>Test4</a></li>
                    <li><a>Test5</a></li>
                </ul>
            </nav>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - testproj - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Storage/PostStorage.cshtml
<form method="POST" asp-action="PostStorage" asp-controller="Storage">
    <label for="StorageName">Storage Name</label>
    <input id="StorageName" name="StorageName" placeholder="storage name goes here" />
    <input type="submit" />
</form>

Views/Storage/Storage.cshtml
@{
    ViewData["Title"] = "Storage";
}

<h1>Storage</h1>

Views/Storage/Storages.cshtml
<table class="table table-bordered" style="width:100%">

    @foreach (var storageName in ViewBag.StorageNames)
    {
        <tr>
            <th>@storageName</th>
            @*<th>Lastname</th>*@
            @*<th>Age</th>*@
        </tr>
    }
</table>